name: Build & Deploy to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    environment: 
      name: SSH
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4 
        with:
          version: 10
          run_install: false
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy to Server
        uses: saranraj3195/sparkout-deployment@v2
        with:
          # SSH private key for authentication
          DEPLOY_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          # SSH username
          USERNAME: '${{ secrets.SSH_USERNAME }}'
          # IP address of the server
          SERVER_IP: '${{ secrets.SSH_SERVER }}'
          # SSH port of the server
          SERVER_PORT: '${{ secrets.SSH_PORT }}'
          # Destination directory on the server
          SERVER_DESTINATION: '${{ secrets.SSH_TARGET }}/AkiLite'
          # Folder to deploy
          FOLDER: 'build'
