name: Build & Deploy to Server

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: "build"
  deploy:
    name: Deploy
    environment:
      name: SSH
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: "build"
      - name: Deploy to Server
        uses: saranraj3195/sparkout-deployment@v2
        env:
          DEPLOY_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          USERNAME: "${{ secrets.SSH_USERNAME }}"
          SERVER_IP: "${{ secrets.SSH_SERVER }}"
          SERVER_PORT: "${{ secrets.SSH_PORT }}"
          SERVER_DESTINATION: "${{ secrets.SSH_TARGET }}/AkiLite/"
          ARGS: "-rtvz --delete"
          FOLDER: "build/*"
